db.url=jdbc:postgresql://localhost:5432/BeU2W3-Project
db.username=postgres
db.password=Succhiamelo98


cloudinary.cloud_name=dgmtadxky
cloudinary.api_key=521197256327851
cloudinary.api_secret=utJKVJCWKD9TWZsDxdABhZhmzNA

jwt.secret=kanyeWestDrakeKendrickLamarNasJColeTravMFDoomEazyE
jwt.expiration=86400000